version: '2'
services:
  web-app-prod:
    container_name: 'web-app-prod'
    build:
      context: .
      dockerfile: docker/web-app/Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb
    command: npm run start

  web-app-dev:
    container_name: 'web-app-dev'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    build:
      context: .
      dockerfile: docker/web-app/Dockerfile
    ports:
      - 8080:8080
    links:
      - mongodb
    depends_on:
      - mongodb
    command: npm run dev

  mongodb:
    image: mongo:latest
    container_name: 'mongodb'
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
